version: '2'
services:
    zoo-1:
        image: zookeeper
        ports:
          - "2181:2181"
    zoo-2:
        image: zookeeper
        ports:
          - "2182:2182"
    zoo-3:
        image: zookeeper
        ports:
          - "2183:2183"
    solr-1:
        image: solr
        ports:
            - 8081:8081
        environment:
            SOLR_PORT: 8081
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
        depends_on:
          - zoo-1
          - zoo-2
          - zoo-3
    solr-2:
        image: solr
        ports:
            - 8082:8082
        environment:
            SOLR_PORT: 8082
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            SOLR_HOST: solr-2
        depends_on:
          - zoo-1
          - zoo-2
          - zoo-3
    solr-3:
        image: solr
        ports:
            - 8083:8083
        environment:
            SOLR_PORT: 8083
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            SOLR_HOST: solr-3
        depends_on:
          - zoo-1
          - zoo-2
          - zoo-3
