version: '2'
services:
    zoo-1:
        image: zookeeper
        restart: always
        ports:
          - 22181:22181
        volumes:
            - /opt/solrcloud/zoo-1:/opt/persist
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 22181
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
    solr-1:
        image: solr
        restart: always
        ports:
            - 9081:9081
        volumes:
            - ./data/solrcloud/solr-1/logs:/opt/logs
            - ./data/solrcloud/solr-1/store:/store
            - ./data/solrcloud/solr-1/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            SOLR_PORT: 9081
#            SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:22181
#            SOLR_LOGS_DIR: /opt/logs
            SOLR_HOST: solr-1
            SOLR_HEAP:
            SOLR_JAVA_MEM:
        depends_on:
          - zoo-1
